### PR TITLE
[f] problem but not sure

### PR DESCRIPTION
**Pull request by gherardovarando**
fixing [issue 45](https://github.com/irenecrsn/gmat/issues/45) 
but need checking, not sure sure why.

### CODE REVIEW

**Comment by irenecrsn** [comment]
Could you please run (in order, should not take too much time)
- https://github.com/irenecrsn/rcor/blob/master/exp_comp.R
- https://github.com/irenecrsn/rcor/blob/master/plot_comp.R
and see if the file `plot/densities_eigen.pdf` generated plots the same density for all methods?

If it does, I'm OK with merging this, even though I don't fully understand why it works. Also, see issue #48 which I just noticed while running the files above. The eigenvalue density is correct even though the matrices sampled with `chol_polar` are not of correlation! Did you expect that?

**Comment by gherardovarando** [comment]
[densities_eigen.pdf](https://github.com/irenecrsn/gmat/files/2632943/densities_eigen.pdf)

**Comment by gherardovarando** [comment]
I think the code is fine, I am just wondering why is not working changing just line [182](https://github.com/irenecrsn/gmat/pull/46/commits/251c8285badb8ef99eac285ca5e565d07efa3d1c#diff-258c064f624cfd6d7c67a79a428c9a57L182) 
to something like:
```
    R[, , n] <- anti_t(tcrossprod(anti_t(L)))
```

without changing line 181

**Comment by irenecrsn** [comment]
I think the same as with issue #48, although now it is solved, it is very interesting and worth further work in the future, at least to have clear the operations we are performing when combining Cholesky decompositions, `t`, `anti_t` and dags. For now I'm going to merge, and change the issue to future work.

**Pull request merged**
